package:
    name: psfgen
    version: 0.0.1

source:
    git_url: https://github.com/Eigenstate/psfgen.git
    git_tag: master

build:
    number: 0

requirements:
    build:
        - python
        - toolchain
    run:
        - python

test:
    requires:
        - pytest
        - vmd-python >=3.0.0
    commands:
        - py.test --pyargs psfgen

about:
    home: https://github.com/Eigenstate/psfgen
    license: VMD
    license_file: LICENSE
    summary: Protein Structure builder, with Python bindings
    doc_url: https://psfgen.robinbetz.com
    dev_url: https://github.com/Eigenstate/psfgen

extra:
    recipe-maintainers:
        - Eigenstate
